# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Test
        run: mkdir /home/runner/.ccache
      - name: Test2  
        run: echo dupa >> /home/runner/.ccache/test.txt
      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
           **/.ccache
          key: ${{ runner.os }}-ccache-${{ github.run_number }}
          restore-keys: ${{ runner.os }}-ccache

      - name: Glob match
        uses: tj-actions/glob@v15
        id: glob
        with:
          files: |
            **/.ccache

      - name: Show all matching files
        run: |
          echo "${{ steps.glob.outputs.paths }}"
         
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
